---
title: "Commandes usuelles en `MAXIMA`"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
header-includes:
  - \usepackage{longtable}
  - \usepackage{booktabs}
  - \usepackage{multirow}
classoption: landscape
geometry: margin=0.5cm
fontsize: 8pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
\begin{longtable}{@{}p{4cm}p{10cm}cc@{}}
\toprule
\textbf{Sujet} & \textbf{Discussion} & \textbf{Entrée \texttt{MAXIMA}} & \textbf{Sortie \texttt{MAXIMA}} \\ 
\midrule
\endhead

\textbf{Entrée de commandes} & Vous devez utiliser le point virgule (\texttt{;}) et \texttt{Ctrl-Entrée} pour effectuer une commande &
5/6*5/6; & $\frac{25}{36}$ \\

\midrule

\textbf{Utilisation de la ligne précédente} & Le symbole (\texttt{\%}) dit à \texttt{MAXIMA} d'utiliser le calcul précédent. &
\%+1; & $\frac{61}{36}$ \\

\midrule

\textbf{Utilisation d'une ligne  par son nom} & Vous pouvez utiliser un résultat à l'aide de sa ligne de sortie. &
\%o2+1; & $\frac{97}{36}$ \\

\midrule

\textbf{Évaluation numérique} & Vous pouvez demander à \texttt{MAXIMA} de calculer la valeur numérique d'un résultat. &
\texttt{float(\%)}; & $2.694444444444445$ \\

\midrule

\multirow{4}{*}{\textbf{Caractères spéciaux}} & $\pi$ : \texttt{\%pi} & \texttt{float(\%pi)}; & $3.141592653589793$ \\
\cmidrule{2-4}
& $e$ : \texttt{\%e} & \texttt{float(\%e)}; & $2.718281828459045$ \\
\cmidrule{2-4}
& $\infty$ : \texttt{inf} & \texttt{inf}; & $\infty$ \\
\cmidrule{2-4}
& $-\infty$ : \texttt{minf} & \texttt{minf}; & $-\infty$ \\

\midrule

\multirow{5}{*}{\textbf{Évaluation numérique}} & Addition : \texttt{+} & \texttt{1+3}; & $4$ \\
\cmidrule{2-4}
& Soustraction : \texttt{-} & \texttt{5-10}; & $-5$ \\
\cmidrule{2-4}
& Multiplication : \texttt{+} & \texttt{2*3}; & $6$ \\
\cmidrule{2-4}
& Division : \texttt{/} & \texttt{5/25}; & $\frac{1}{5}$ \\
\cmidrule{2-4}
& Puissance : $\wedge$ & \texttt{3$\wedge$2}; & $9$ \\

\midrule

\textbf{Définir une fonction} & Pour définir une fonction, vous lui donnez un nom, suivi par sa variable indépendante entre parenthèses, suivis par le symbole \texttt{:=}, suivi par sa définition. &
\texttt{f1(x):=x$\wedge$2-5*x+6}; & $f1(x):=x^2-5x+6$ \\

\midrule

\textbf{Évaluation d'une fonction} & Une fois définie, vous pouvez utiliser la fonction de la même façon que vous le feriez habituellement. &
\texttt{f1(5)}; & $6$ \\

\midrule

\multirow{2}{4cm}{\textbf{Assignation d'une valeur à une variable}} & Le symbole \texttt{:} assigne une valeur à une variable. & \texttt{a:5}; & $5$ \\
\cmidrule{2-4}
& La valeur associée à la variable sera maintenant utilisée à la place du nom de la variable. & \texttt{f1(a)}; & $6$ \\

\midrule

\textbf{Définir une équation} & Le symbole \texttt{=} défini une équation. & \texttt{x$\wedge$2+5*x+6=0}; & $x^2+5x+6=0$ \\

\midrule

\textbf{Assignation d'une expression à une variable} & Vous pouvez utiliser le symbole \texttt{:} pour assigner une équation à une variable. & \texttt{e1:x$\wedge$2+5*x+6=0}; & $x^2+5x+6=0$ \\

\midrule

\multirow{3}{4cm}{\textbf{Résoudre une équation}} & Vous pouvez utiliser la commande \texttt{solve} pour résoudre une équation. Vous entrez en premier lieu l'équation à résoudre, suivie par une virgule et la variable par rapport à laquelle vous voulez résoudre. & \texttt{solve(2*x+1=3,x)}; & $[x=1]$ \\
\cmidrule{2-4}
& Un autre exemple qui résout une équation quadratique. & \texttt{sol:solve(x$\wedge$2+2*x-3=0,x)}; & $[x=-3,x=1]$ \\
\cmidrule{2-4}
& Vous pouvez utiliser les résultats obtenus à l'aide de la commande \texttt{solve} en effectuant une extraction. & \texttt{sol[2]}; & $x=1$ \\

\midrule

\textbf{Substitution de résultats d'un calcul dans un autre} & Nous pouvons éviter de retaper des résultats en utilisant une substitution \texttt{subst}. Vous entrez en premier lieu la valeur à substituer suivie d'une virgule. Vous entrez enfin l'équation dans laquelle vous voulez substituer la valeur. & \texttt{subst(sol[2],y=3*x-11)}; & $-8$ \\

\midrule

\textbf{Factorisation de polynômes} & Il est possible de factoriser des polynômes avec \texttt{MAXIMA} en utilisant la commande \texttt{factor}. & \texttt{factor(x$\wedge$2+2*x+1)}; & $(x+1)^2$ \\

\midrule

\textbf{Développement de polynômes} & Il est possible de développer des polynômes avec \texttt{MAXIMA} en utilisant la commande \texttt{expand}. & \texttt{expand((x+3)*(x+1))}; & $x^2+4x+3$ \\

\midrule

\textbf{Simplification d'expressions trigonométriques} & Il est possible de simplifier des expressions trigonométriques avec \texttt{MAXIMA} en utilisant la commande \texttt{trigsimp}. & \texttt{trigsimp(sin(x)$\wedge$2+cos(x)$\wedge$2)}; & $1$ \\

\midrule

\textbf{Développement d'expressions trigonométriques} & Il est possible de développer des expressions trigonométriques avec \texttt{MAXIMA} en utilisant la commande \texttt{trigexpand}. & \texttt{trigexpand(cos(x+3*y))}; & $\cos{(x)}\,\cos{(3y)}-\sin{(x)}\,\sin{(3y)}$ \\

\midrule

\textbf{Simplification d'expressions rationnelles} & Il est possible de simplifier des expressions rationnelles avec \texttt{MAXIMA} en utilisant la commande \texttt{fullratsimp}. & \tiny{\texttt{fullratsimp((x$\wedge$2+2*x+1)/(x+1)+1/(4*x+3))}}; & $\frac{4{{x}^{2}}+7x+4}{4x+3}$ \\

\midrule

\textbf{Développement d'expressions rationnelles} & Il est possible de développer des expressions rationnelles avec \texttt{MAXIMA} en utilisant la commande \texttt{ratexpand}. & \texttt{ratexpand((x$\wedge$2-1)/(x+2))}; & $\frac{{{x}^{2}}}{x+2}-\frac{1}{x+2}$ \\

\bottomrule
\end{longtable}
\end{center}